apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    app: apache
spec:
  containers:
  - name: apache-container
    image: narsingdev/apache
    ports:
    - name: apache-port
      containerPort: 80
